# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'X-Things-I-Love-About-You' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for X-Things-I-Love-About-You
  pod 'SOTabBar'
end